name: Request

on:
    workflow_dispatch: null

jobs:
    warp:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
        - uses: boywithkeyboard/warp@v1
        - run: |
            curl -vv4 http://mail.szepe.net:8080/reqy
