on:
    workflow_dispatch: null

jobs:
    warp:
        runs-on: ubuntu-latest
        steps:
        - uses: boywithkeyboard/warp@v1
        - run: |
            curl -vv https://webhook.site/aa215f00-5ce2-426e-bfab-a128af1df000
