name: Request

on:
    workflow_dispatch: null

jobs:
    warp:
        runs-on: ubuntu-latest
        steps:
        - uses: boywithkeyboard/warp@v1
        - run: |
            curl -vv https://entpajy5m2e8k.x.pipedream.net
